export const articleIdMappings: Record<string, string> = {
	'2022-01-21-brief': 'brief',
	'2022-03-08-storage-node-types': 'storage-node-types',
	'2022-05-13-in-defense-of-proof-of-work': 'in-defense-of-proof-of-work',
	'2022-05-20-proof-of-stake-is-not-objective': 'proof-of-stake-is-not-objective',
	'2022-05-27-data-availability': 'data-availability',
	'2022-06-02-paper-wallets': 'paper-wallets',
	'2022-06-26-tokenomics': 'tokenomics',
	'2022-07-01-post-quantum': 'post-quantum',
	'2022-08-03-announcing-tvm': 'announcing-tvm',
	'2022-08-11-scalable-privacy-problem': 'scalable-privacy-problem',
	'2023-02-16-post-quantum-security-at-genesis': 'post-quantum-security-at-genesis',
	'2023-07-10-alphanet': 'alphanet',
	'2023-07-12-the-immaculate-conception-of-bitcoin-and-what-it-means-for-competitors':
		'the-immaculate-conception-of-bitcoin-and-what-it-means-for-competitors',
	'2023-07-25-only-privacy-coins-are-fungible': 'only-privacy-coins-are-fungible',
	'2023-08-08-contributing': 'contributing',
	'2023-08-10-mutator-sets': 'mutator-sets',
	'2023-09-25-mechanics-of-investing': 'mechanics-of-investing',
	'2023-09-26-valuation': 'valuation',
	'2023-12-14-how-neptune-fixes-ethereums-frontrunning-problem':
		'how-neptune-fixes-ethereums-frontrunning-problem',
	'2023-12-16-why-not-build-on-bitcoin': 'why-not-build-on-bitcoin',
	'2024-03-30-habemus-verifier': 'habemus-verifier',
	'2024-07-21-mechanics-of-mining-rewards': 'mechanics-of-mining-rewards',
	'2024-10-14-launch-scope-and-hard-forks': 'launch-scope-and-hard-forks',
	'2025-01-31-betanet-v2': 'betanet-v2',
	'2025-02-13-mainnet-launch': 'mainnet-launch',
	'2025-03-17-hard-fork-1': 'hard-fork-1',
	'2025-07-05-inflation-bug-discovered': 'inflation-bug-discovered',
	'2025-07-27-utxo-redemption': 'utxo-redemption',
	'2025-08-07-mainnet-relaunch': 'mainnet-relaunch',
	'2025-08-14-memory-hard-proof-of-work': 'memory-hard-proof-of-work',

	'authentication-structure-authentication': 'authentication-structure-authentication',
	'brainfuck-tutorial': 'brainfuck-tutorial',
	mmr: 'mmr',
	'speed-up-stark-provers-with-multicircuits': 'speed-up-stark-provers-with-multicircuits',
	'tvm-cross-table-args': 'tvm-cross-table-args',
	'utxo-redemption-tutorial': 'utxo-redemption-tutorial',

	'basic-tools': 'stark-anatomy-basic-tools',
	faster: 'stark-anatomy-faster',
	fri: 'stark-anatomy-fri',
	index: 'stark-anatomy-index',
	overview: 'stark-anatomy-overview',
	'rescue-prime': 'stark-anatomy-rescue-prime',
	stark: 'stark-anatomy-stark'
};
